version: '3'

services:
  db:
    container_name: customers_db
    image: postgres
    environment:
      POSTGRES_USER: customers
      POSTGRES_PASSWORD: customers
      POSTGRES_DB: dbname
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    container_name: issuer
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  postgres_data: