version: '3'

services:
  db:
    container_name: customers_db
    image: postgres
    environment:
      POSTGRES_USER: customers
      POSTGRES_PASSWORD: customers
      POSTGRES_DB: customers
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U customers"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    container_name: issuer
    build: .
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: