# Generated by Django 4.1 on 2024-04-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_policy_options_alter_policy_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='policy_number',
        ),
        migrations.AddField(
            model_name='policy',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
