name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    needs:
      - build
      - test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          remote_path: /home/ubuntu/policy_issuer/
          remote_host: ec2-18-135-45-9.eu-west-2.compute.amazonaws.com
          remote_user: ubuntu
          remote_key: "${{ secrets.SECRET_KEY }}"

      - name: Deploy to AWS
        run: |
          docker compose up -d --build
