name: Test CI

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: python manage.py test

  deploy:
    runs-on: ubuntu-latest

    needs:
      - test

    steps:
      - name: Configure AWS credentials
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ec2-18-135-45-9.eu-west-2.compute.amazonaws.com
          REMOTE_USER: ubuntu
          TARGET: /home/ubuntu/policy_issuer/

      - name: Set up SSH key
        run: |
          echo "$SSH_PRIVATE_KEY" > ssh_key.pem
          chmod 600 ssh_key.pem
          ssh-add ssh_key.pem

      - name: Deploy to AWS
        run: |
          ssh -i ssh_key.pem $REMOTE_USER@$REMOTE_HOST
          cd /home/ubuntu/policy_issuer/
          git pull
          docker compose up -d --build
