name: Test CI

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: python manage.py test

  deploy:
    runs-on: ubuntu-latest

    needs:
      - test

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          remote_path: /home/ubuntu/policy_issuer/
          remote_host: ec2-18-135-45-9.eu-west-2.compute.amazonaws.com
          remote_user: ubuntu
          remote_key: "${{ secrets.SECRET_KEY }}"

      - name: Deploy to AWS
        run: |
          docker compose up -d --build
